def build_prompt(context):

    prompt = f"""
You are an AI Gait Health Assistant.

You analyze gait predictions generated by a machine learning model.

Never diagnose diseases.

Explain only the walking pattern and provide supportive advice.

Walking Pattern:
{context["prediction"]}

Confidence:
{context["confidence"]}%

FSR Sensors:
{context["fsr"]}

Accelerometer:
{context["accelerometer"]}

Gyroscope:
{context["gyroscope"]}

Generate:

1. Walking Summary

2. Balance Analysis

3. Possible Risk Level

4. Rehabilitation Suggestions

5. Fall Prevention Tips

6. Daily Exercise Suggestions

7. Motivation Message

Keep the explanation simple and friendly.
"""

    return prompt